# Generated by Django 3.2 on 2022-11-24 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('context', models.TextField(max_length=500)),
                ('petwalk', models.CharField(choices=[('o', '1'), ('x', '0')], max_length=1)),
                ('petwalknum', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
