# Generated by Django 3.2 on 2022-11-24 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('petname', models.CharField(blank=True, max_length=10, null=True)),
                ('petyear', models.DateField(blank=True, null=True)),
                ('petspecies', models.CharField(blank=True, max_length=20, null=True)),
                ('petweight', models.FloatField(blank=True, null=True)),
                ('petpublicnum', models.IntegerField(blank=True, null=True)),
                ('petsex', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True)),
                ('petdesex', models.CharField(blank=True, choices=[('O', '1'), ('X', '0')], max_length=1, null=True)),
                ('petimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('noseprint', models.CharField(blank=True, choices=[('O', '1'), ('X', '0')], max_length=1, null=True)),
                ('noseimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
