# Generated by Django 3.2 on 2022-11-21 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hospital_name', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
                ('required', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalnameing', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccination', models.DateField(blank=True, null=True)),
                ('heartworm', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
